apiVersion: v1
kind: Service
metadata:
  name: python-helloworld-service

spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      name: http

  selector:
    app: my-python-hello-app
    type: backend-python